[build]
  base = ""
  publish = "build/"
  command = "npm run build"
  # functions = "project/functions/"

  [build.processing]
    skip_processing = false
  [build.processing.css]
    bundle = false
    minify = false
  [build.processing.js]
    bundle = false
    minify = false
  [build.processing.html]
    pretty_urls = false
  [build.processing.images]
    compress = true


[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    X-Permitted-Cross-Domain-Policies = "none"
    Referrer-Policy = "SAME-ORIGIN"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    # Content-Security-Policy = '''
    #   default-src 'none';
    #   script-src https://analytics.lucacastelnuovo.nl/tracker.js https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js https://www.google.com/recaptcha/api.js https://www.gstatic.com/recaptcha/releases/ 'sha256-pqbLoUivu70DlJASohKPjOwAI8Wbu5KIcoQm6724w1s=' 'sha256-Cd9/QKWARPyeNkN5xsQ7cEmWnVmRMHGieDedY+RS6dU=';
    #   style-src 'unsafe-inline' https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css https://fonts.googleapis.com/icon;
    #   img-src 'self' https://*.cloudfront.net;
    #   frame-src 'self' https://www.google.com/recaptcha/api2/anchor;
    #   font-src https://fonts.googleapis.com/icon https://fonts.gstatic.com/s/materialicons/;
    #   connect-src 'self' https://analytics.lucacastelnuovo.nl;
    # '''

[[headers]]
  for = "/static/*"

  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

#######
# PDF #
#######
[[redirects]]
  from = "/cv"
  to = "/pdf/cv.pdf"

########
# Keys #
########
[[redirects]]
  from = "/ssh"
  to = "/keys/ssh-13377661.txt"

[[redirects]]
  from = "/pgp"
  to = "/keys/pgp-13377661.txt"

###########
# Socials #
###########
[[redirects]]
  from = "/github"
  to = "https://github.com/Luca-Castelnuovo"

[[redirects]]
  from = "/instagram"
  to = "https://www.instagram.com/ltcastelnuovo"

[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/ltcastelnuovo/"

[[redirects]]
  from = "/snapchat"
  to = "https://www.snapchat.com/add/ltcastelnuovo"

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/LucaCastelnuovo"

#########
# Other #
#########
[[redirects]]
  from = "/paypal"
  to = "http://paypal.me/ltcastelnuovo"
