import hetHakHout from 'assets/projects/hetHakHout.webp';

const Projects = [
    {
        title: 'Het Hak Hout',
        description:
            'Natuurervaring in een unieke omgeving, Een historisch landschap langs de Kromme Rijn. Een verborgen juweel van de provincie Utrecht. Ervaar Shinrin-Yuku, wandel langs kastelen en door het bos, traditioneel boogschieten, vogelspotten, Een stilte retraite of huur een cabin.',
        image: hetHakHout,
        tags: ['React', 'Bulma', 'Directus'],
        demo_link: 'https://hethakhout.nl',
        github_link: null,
    },
    {
        title: 'TechAssistants Soest',
        description: 'blah',
        image: hetHakHout,
        tags: ['Eleventy', 'MaterializeCSS'],
        demo_link: 'https://ta-soest.nl',
        github_link: 'https://github.com/Luca-Castelnuovo/TA-Soest',
    },
    {
        title: 'Het Hak Hout',
        description: 'blah',
        image: hetHakHout,
        tags: ['React', 'Bulma', 'Directus'],
        demo_link: 'https://hethakhout.nl',
        github_link: null,
    },
    {
        title: 'Het Hak Hout',
        description: 'blah',
        image: hetHakHout,
        tags: ['React', 'Bulma', 'Directus'],
        demo_link: 'https://hethakhout.nl',
        github_link: null,
    },
    {
        title: 'Het Hak Hout',
        description: 'blah',
        image: hetHakHout,
        tags: ['React', 'Bulma', 'Directus'],
        demo_link: 'https://hethakhout.nl',
        github_link: null,
    },
    {
        title: 'Het Hak Hout',
        description: 'blah',
        image: hetHakHout,
        tags: ['React', 'Bulma', 'Directus'],
        demo_link: 'https://hethakhout.nl',
        github_link: null,
    },
    {
        title: 'Het Hak Hout',
        description: 'blah',
        image: hetHakHout,
        tags: ['React', 'Bulma', 'Directus'],
        demo_link: 'https://hethakhout.nl',
        github_link: null,
    },
    {
        title: 'Het Hak Hout',
        description: 'blah',
        image: hetHakHout,
        tags: ['React', 'Bulma', 'Directus'],
        demo_link: 'https://hethakhout.nl',
        github_link: null,
    },
    {
        title: 'Het Hak Hout',
        description: 'blah',
        image: hetHakHout,
        tags: ['React', 'Bulma', 'Directus'],
        demo_link: 'https://hethakhout.nl',
        github_link: null,
    },
    {
        title: 'Het Hak Hout',
        description: 'blah',
        image: hetHakHout,
        tags: ['React', 'Bulma', 'Directus'],
        demo_link: 'https://hethakhout.nl',
        github_link: null,
    },
    {
        title: 'Het Hak Hout',
        description: 'blah',
        image: hetHakHout,
        tags: ['React', 'Bulma', 'Directus'],
        demo_link: 'https://hethakhout.nl',
        github_link: null,
    },
    {
        title: 'Het Hak Hout',
        description: 'blah',
        image: hetHakHout,
        tags: ['React', 'Bulma', 'Directus'],
        demo_link: 'https://hethakhout.nl',
        github_link: null,
    },
    {
        title: 'Het Hak Hout',
        description: 'blah',
        image: hetHakHout,
        tags: ['React', 'Bulma', 'Directus'],
        demo_link: 'https://hethakhout.nl',
        github_link: null,
    },
    {
        title: 'Het Hak Hout',
        description: 'blah',
        image: hetHakHout,
        tags: ['React', 'Bulma', 'Directus'],
        demo_link: 'https://hethakhout.nl',
        github_link: null,
    },
    {
        title: 'Het Hak Hout',
        description: 'blah',
        image: hetHakHout,
        tags: ['React', 'Bulma', 'Directus'],
        demo_link: 'https://hethakhout.nl',
        github_link: null,
    },
    {
        title: 'Het Hak Hout',
        description: 'blah',
        image: hetHakHout,
        tags: ['React', 'Bulma', 'Directus'],
        demo_link: 'https://hethakhout.nl',
        github_link: null,
    },
    {
        title: 'Het Hak Hout',
        description: 'blah',
        image: hetHakHout,
        tags: ['React', 'Bulma', 'Directus'],
        demo_link: 'https://hethakhout.nl',
        github_link: null,
    },
    {
        title: 'Het Hak Hout',
        description: 'blah',
        image: hetHakHout,
        tags: ['React', 'Bulma', 'Directus'],
        demo_link: 'https://hethakhout.nl',
        github_link: null,
    },
    {
        title: 'Het Hak Hout',
        description: 'blah',
        image: hetHakHout,
        tags: ['React', 'Bulma', 'Directus'],
        demo_link: 'https://hethakhout.nl',
        github_link: null,
    },
];

export default Projects;
